/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as RecordingsIndexRouteImport } from './routes/recordings/index'
import { Route as RadioIndexRouteImport } from './routes/radio/index'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as SettingsSubsonicRouteImport } from './routes/settings/subsonic'
import { Route as SettingsHistoryRouteImport } from './routes/settings/history'
import { Route as SettingsAudioRouteImport } from './routes/settings/audio'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsAboutRouteImport } from './routes/settings/about'
import { Route as LibraryStationsIndexRouteImport } from './routes/library/stations/index'
import { Route as LibrarySongsIndexRouteImport } from './routes/library/songs/index'
import { Route as LibraryPlaylistsIndexRouteImport } from './routes/library/playlists/index'
import { Route as LibraryArtistsIndexRouteImport } from './routes/library/artists/index'
import { Route as LibraryAlbumsIndexRouteImport } from './routes/library/albums/index'
import { Route as ArtistArtistIdIndexRouteImport } from './routes/artist/$artistId/index'
import { Route as AlbumAlbumIdIndexRouteImport } from './routes/album/$albumId/index'
import { Route as LibraryPlaylistsPlaylistIdIndexRouteImport } from './routes/library/playlists/$playlistId/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsIndexRoute = RecordingsIndexRouteImport.update({
  id: '/recordings/',
  path: '/recordings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioIndexRoute = RadioIndexRouteImport.update({
  id: '/radio/',
  path: '/radio/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSubsonicRoute = SettingsSubsonicRouteImport.update({
  id: '/subsonic',
  path: '/subsonic',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsHistoryRoute = SettingsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAudioRoute = SettingsAudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const LibraryStationsIndexRoute = LibraryStationsIndexRouteImport.update({
  id: '/library/stations/',
  path: '/library/stations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySongsIndexRoute = LibrarySongsIndexRouteImport.update({
  id: '/library/songs/',
  path: '/library/songs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryPlaylistsIndexRoute = LibraryPlaylistsIndexRouteImport.update({
  id: '/library/playlists/',
  path: '/library/playlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryArtistsIndexRoute = LibraryArtistsIndexRouteImport.update({
  id: '/library/artists/',
  path: '/library/artists/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryAlbumsIndexRoute = LibraryAlbumsIndexRouteImport.update({
  id: '/library/albums/',
  path: '/library/albums/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistArtistIdIndexRoute = ArtistArtistIdIndexRouteImport.update({
  id: '/artist/$artistId/',
  path: '/artist/$artistId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumAlbumIdIndexRoute = AlbumAlbumIdIndexRouteImport.update({
  id: '/album/$albumId/',
  path: '/album/$albumId/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryPlaylistsPlaylistIdIndexRoute =
  LibraryPlaylistsPlaylistIdIndexRouteImport.update({
    id: '/library/playlists/$playlistId/',
    path: '/library/playlists/$playlistId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/audio': typeof SettingsAudioRoute
  '/settings/history': typeof SettingsHistoryRoute
  '/settings/subsonic': typeof SettingsSubsonicRoute
  '/library/': typeof LibraryIndexRoute
  '/radio/': typeof RadioIndexRoute
  '/recordings/': typeof RecordingsIndexRoute
  '/search/': typeof SearchIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/album/$albumId/': typeof AlbumAlbumIdIndexRoute
  '/artist/$artistId/': typeof ArtistArtistIdIndexRoute
  '/library/albums/': typeof LibraryAlbumsIndexRoute
  '/library/artists/': typeof LibraryArtistsIndexRoute
  '/library/playlists/': typeof LibraryPlaylistsIndexRoute
  '/library/songs/': typeof LibrarySongsIndexRoute
  '/library/stations/': typeof LibraryStationsIndexRoute
  '/library/playlists/$playlistId/': typeof LibraryPlaylistsPlaylistIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/audio': typeof SettingsAudioRoute
  '/settings/history': typeof SettingsHistoryRoute
  '/settings/subsonic': typeof SettingsSubsonicRoute
  '/library': typeof LibraryIndexRoute
  '/radio': typeof RadioIndexRoute
  '/recordings': typeof RecordingsIndexRoute
  '/search': typeof SearchIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/album/$albumId': typeof AlbumAlbumIdIndexRoute
  '/artist/$artistId': typeof ArtistArtistIdIndexRoute
  '/library/albums': typeof LibraryAlbumsIndexRoute
  '/library/artists': typeof LibraryArtistsIndexRoute
  '/library/playlists': typeof LibraryPlaylistsIndexRoute
  '/library/songs': typeof LibrarySongsIndexRoute
  '/library/stations': typeof LibraryStationsIndexRoute
  '/library/playlists/$playlistId': typeof LibraryPlaylistsPlaylistIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/audio': typeof SettingsAudioRoute
  '/settings/history': typeof SettingsHistoryRoute
  '/settings/subsonic': typeof SettingsSubsonicRoute
  '/library/': typeof LibraryIndexRoute
  '/radio/': typeof RadioIndexRoute
  '/recordings/': typeof RecordingsIndexRoute
  '/search/': typeof SearchIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/album/$albumId/': typeof AlbumAlbumIdIndexRoute
  '/artist/$artistId/': typeof ArtistArtistIdIndexRoute
  '/library/albums/': typeof LibraryAlbumsIndexRoute
  '/library/artists/': typeof LibraryArtistsIndexRoute
  '/library/playlists/': typeof LibraryPlaylistsIndexRoute
  '/library/songs/': typeof LibrarySongsIndexRoute
  '/library/stations/': typeof LibraryStationsIndexRoute
  '/library/playlists/$playlistId/': typeof LibraryPlaylistsPlaylistIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/audio'
    | '/settings/history'
    | '/settings/subsonic'
    | '/library/'
    | '/radio/'
    | '/recordings/'
    | '/search/'
    | '/settings/'
    | '/album/$albumId/'
    | '/artist/$artistId/'
    | '/library/albums/'
    | '/library/artists/'
    | '/library/playlists/'
    | '/library/songs/'
    | '/library/stations/'
    | '/library/playlists/$playlistId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/audio'
    | '/settings/history'
    | '/settings/subsonic'
    | '/library'
    | '/radio'
    | '/recordings'
    | '/search'
    | '/settings'
    | '/album/$albumId'
    | '/artist/$artistId'
    | '/library/albums'
    | '/library/artists'
    | '/library/playlists'
    | '/library/songs'
    | '/library/stations'
    | '/library/playlists/$playlistId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/audio'
    | '/settings/history'
    | '/settings/subsonic'
    | '/library/'
    | '/radio/'
    | '/recordings/'
    | '/search/'
    | '/settings/'
    | '/album/$albumId/'
    | '/artist/$artistId/'
    | '/library/albums/'
    | '/library/artists/'
    | '/library/playlists/'
    | '/library/songs/'
    | '/library/stations/'
    | '/library/playlists/$playlistId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  LibraryIndexRoute: typeof LibraryIndexRoute
  RadioIndexRoute: typeof RadioIndexRoute
  RecordingsIndexRoute: typeof RecordingsIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  AlbumAlbumIdIndexRoute: typeof AlbumAlbumIdIndexRoute
  ArtistArtistIdIndexRoute: typeof ArtistArtistIdIndexRoute
  LibraryAlbumsIndexRoute: typeof LibraryAlbumsIndexRoute
  LibraryArtistsIndexRoute: typeof LibraryArtistsIndexRoute
  LibraryPlaylistsIndexRoute: typeof LibraryPlaylistsIndexRoute
  LibrarySongsIndexRoute: typeof LibrarySongsIndexRoute
  LibraryStationsIndexRoute: typeof LibraryStationsIndexRoute
  LibraryPlaylistsPlaylistIdIndexRoute: typeof LibraryPlaylistsPlaylistIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings/': {
      id: '/recordings/'
      path: '/recordings'
      fullPath: '/recordings/'
      preLoaderRoute: typeof RecordingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio/': {
      id: '/radio/'
      path: '/radio'
      fullPath: '/radio/'
      preLoaderRoute: typeof RadioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/subsonic': {
      id: '/settings/subsonic'
      path: '/subsonic'
      fullPath: '/settings/subsonic'
      preLoaderRoute: typeof SettingsSubsonicRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/history': {
      id: '/settings/history'
      path: '/history'
      fullPath: '/settings/history'
      preLoaderRoute: typeof SettingsHistoryRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/audio': {
      id: '/settings/audio'
      path: '/audio'
      fullPath: '/settings/audio'
      preLoaderRoute: typeof SettingsAudioRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/library/stations/': {
      id: '/library/stations/'
      path: '/library/stations'
      fullPath: '/library/stations/'
      preLoaderRoute: typeof LibraryStationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/songs/': {
      id: '/library/songs/'
      path: '/library/songs'
      fullPath: '/library/songs/'
      preLoaderRoute: typeof LibrarySongsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/playlists/': {
      id: '/library/playlists/'
      path: '/library/playlists'
      fullPath: '/library/playlists/'
      preLoaderRoute: typeof LibraryPlaylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/artists/': {
      id: '/library/artists/'
      path: '/library/artists'
      fullPath: '/library/artists/'
      preLoaderRoute: typeof LibraryArtistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/albums/': {
      id: '/library/albums/'
      path: '/library/albums'
      fullPath: '/library/albums/'
      preLoaderRoute: typeof LibraryAlbumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$artistId/': {
      id: '/artist/$artistId/'
      path: '/artist/$artistId'
      fullPath: '/artist/$artistId/'
      preLoaderRoute: typeof ArtistArtistIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$albumId/': {
      id: '/album/$albumId/'
      path: '/album/$albumId'
      fullPath: '/album/$albumId/'
      preLoaderRoute: typeof AlbumAlbumIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/playlists/$playlistId/': {
      id: '/library/playlists/$playlistId/'
      path: '/library/playlists/$playlistId'
      fullPath: '/library/playlists/$playlistId/'
      preLoaderRoute: typeof LibraryPlaylistsPlaylistIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsAudioRoute: typeof SettingsAudioRoute
  SettingsHistoryRoute: typeof SettingsHistoryRoute
  SettingsSubsonicRoute: typeof SettingsSubsonicRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsAudioRoute: SettingsAudioRoute,
  SettingsHistoryRoute: SettingsHistoryRoute,
  SettingsSubsonicRoute: SettingsSubsonicRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRouteWithChildren,
  LibraryIndexRoute: LibraryIndexRoute,
  RadioIndexRoute: RadioIndexRoute,
  RecordingsIndexRoute: RecordingsIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  AlbumAlbumIdIndexRoute: AlbumAlbumIdIndexRoute,
  ArtistArtistIdIndexRoute: ArtistArtistIdIndexRoute,
  LibraryAlbumsIndexRoute: LibraryAlbumsIndexRoute,
  LibraryArtistsIndexRoute: LibraryArtistsIndexRoute,
  LibraryPlaylistsIndexRoute: LibraryPlaylistsIndexRoute,
  LibrarySongsIndexRoute: LibrarySongsIndexRoute,
  LibraryStationsIndexRoute: LibraryStationsIndexRoute,
  LibraryPlaylistsPlaylistIdIndexRoute: LibraryPlaylistsPlaylistIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
