/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RecordingsIndexRouteImport } from './routes/recordings/index'
import { Route as MapIndexRouteImport } from './routes/map/index'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as SettingsHistoryRouteImport } from './routes/settings/history'
import { Route as SettingsAudioRouteImport } from './routes/settings/audio'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsAboutRouteImport } from './routes/settings/about'
import { Route as LibraryStationsIndexRouteImport } from './routes/library/stations/index'
import { Route as LibraryPlaylistsIndexRouteImport } from './routes/library/playlists/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const RecordingsIndexRoute = RecordingsIndexRouteImport.update({
  id: '/recordings/',
  path: '/recordings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapIndexRoute = MapIndexRouteImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHistoryRoute = SettingsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAudioRoute = SettingsAudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const LibraryStationsIndexRoute = LibraryStationsIndexRouteImport.update({
  id: '/library/stations/',
  path: '/library/stations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryPlaylistsIndexRoute = LibraryPlaylistsIndexRouteImport.update({
  id: '/library/playlists/',
  path: '/library/playlists/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/audio': typeof SettingsAudioRoute
  '/settings/history': typeof SettingsHistoryRoute
  '/library/': typeof LibraryIndexRoute
  '/map/': typeof MapIndexRoute
  '/recordings/': typeof RecordingsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/library/playlists/': typeof LibraryPlaylistsIndexRoute
  '/library/stations/': typeof LibraryStationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/audio': typeof SettingsAudioRoute
  '/settings/history': typeof SettingsHistoryRoute
  '/library': typeof LibraryIndexRoute
  '/map': typeof MapIndexRoute
  '/recordings': typeof RecordingsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/library/playlists': typeof LibraryPlaylistsIndexRoute
  '/library/stations': typeof LibraryStationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/audio': typeof SettingsAudioRoute
  '/settings/history': typeof SettingsHistoryRoute
  '/library/': typeof LibraryIndexRoute
  '/map/': typeof MapIndexRoute
  '/recordings/': typeof RecordingsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/library/playlists/': typeof LibraryPlaylistsIndexRoute
  '/library/stations/': typeof LibraryStationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/audio'
    | '/settings/history'
    | '/library/'
    | '/map/'
    | '/recordings/'
    | '/settings/'
    | '/library/playlists/'
    | '/library/stations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/audio'
    | '/settings/history'
    | '/library'
    | '/map'
    | '/recordings'
    | '/settings'
    | '/library/playlists'
    | '/library/stations'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/audio'
    | '/settings/history'
    | '/library/'
    | '/map/'
    | '/recordings/'
    | '/settings/'
    | '/library/playlists/'
    | '/library/stations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  LibraryIndexRoute: typeof LibraryIndexRoute
  MapIndexRoute: typeof MapIndexRoute
  RecordingsIndexRoute: typeof RecordingsIndexRoute
  LibraryPlaylistsIndexRoute: typeof LibraryPlaylistsIndexRoute
  LibraryStationsIndexRoute: typeof LibraryStationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/recordings/': {
      id: '/recordings/'
      path: '/recordings'
      fullPath: '/recordings/'
      preLoaderRoute: typeof RecordingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/': {
      id: '/map/'
      path: '/map'
      fullPath: '/map/'
      preLoaderRoute: typeof MapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/history': {
      id: '/settings/history'
      path: '/history'
      fullPath: '/settings/history'
      preLoaderRoute: typeof SettingsHistoryRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/audio': {
      id: '/settings/audio'
      path: '/audio'
      fullPath: '/settings/audio'
      preLoaderRoute: typeof SettingsAudioRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/library/stations/': {
      id: '/library/stations/'
      path: '/library/stations'
      fullPath: '/library/stations/'
      preLoaderRoute: typeof LibraryStationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/playlists/': {
      id: '/library/playlists/'
      path: '/library/playlists'
      fullPath: '/library/playlists/'
      preLoaderRoute: typeof LibraryPlaylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsAudioRoute: typeof SettingsAudioRoute
  SettingsHistoryRoute: typeof SettingsHistoryRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsAudioRoute: SettingsAudioRoute,
  SettingsHistoryRoute: SettingsHistoryRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRouteWithChildren,
  LibraryIndexRoute: LibraryIndexRoute,
  MapIndexRoute: MapIndexRoute,
  RecordingsIndexRoute: RecordingsIndexRoute,
  LibraryPlaylistsIndexRoute: LibraryPlaylistsIndexRoute,
  LibraryStationsIndexRoute: LibraryStationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
